### ISSUE TITLE
Unable to load plugin with QGIS 3.0.0

### ISSUE THREAD

**Issue by cbredel** [webgeodatavore/bivariate_legend#2]
I can't load the plugin. 

I'm on Windows 10 with QGIS 3.0.0 64bits 

When I try to activate the extension, i have the error below. 
For information, I try to import the QgsMapLayerComboBox module in the Python Console (from qgis.gui import QgsMapLayerComboBox) and I don't have error. 

Do you have a solution for my problem ? 
Thank 

Impossible de charger l'extension 'BivariateLegend' provoque une erreur lors de l'appel à sa méthode classFactory() 

ModuleNotFoundError: No module named 'qgsmaplayercombobox' 
Traceback (most recent call last):
  File "C:/_oss/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/cbredel.AGAPE-PED/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BivariateLegend\__init__.py", line 34, in classFactory
    from .bivariate_legend import BivariateLegend
  File "C:/_oss/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/cbredel.AGAPE-PED/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BivariateLegend\bivariate_legend.py", line 38, in 
    from .bivariate_legend_dockwidget import BivariateLegendDockWidget
  File "C:/_oss/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/cbredel.AGAPE-PED/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BivariateLegend\bivariate_legend_dockwidget.py", line 30, in 
    os.path.dirname(__file__), 'bivariate_legend_dockwidget_base.ui'))
  File "C:\_oss\QGIS3~1.0\apps\Python36\lib\site-packages\PyQt5\uic\__init__.py", line 201, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 91, in 
  File "C:/_oss/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'qgsmaplayercombobox'

Version de Python : 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Version de QGIS : 3.0.0-Girona Girona, 001c80b0c3 

Chemin Python :
C:/_oss/QGIS3~1.0/apps/qgis/./python
C:/Users/cbredel.AGAPE-PED/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/cbredel.AGAPE-PED/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/_oss/QGIS3~1.0/apps/qgis/./python/plugins
C:\_oss\QGIS 3.0\bin\python36.zip
C:\_oss\QGIS3~1.0\apps\Python36\DLLs
C:\_oss\QGIS3~1.0\apps\Python36\lib
C:\_oss\QGIS 3.0\bin
C:\_oss\QGIS3~1.0\apps\Python36
C:\_oss\QGIS3~1.0\apps\Python36\lib\site-packages
C:/Users/cbredel.AGAPE-PED/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by ThomasG77** [comment]
Hi,

Can you replace the following in the file [bivariate_legend_dockwidget_base.ui](https://github.com/webgeodatavore/bivariate_legend/blob/0c515af62e83eeec89dd1e5858b754887ec04e15/bivariate_legend_dockwidget_base.ui#L140) ?

```
  <customwidget>
   <class>QgsMapLayerComboBox</class>
   <extends>QComboBox</extends>
   <header>qgsmaplayercombobox.h</header>
</customwidget>
```
with

```
  <customwidget>
   <class>QgsMapLayerComboBox</class>
   <extends>QComboBox</extends>
   <header>qgis.gui</header>
</customwidget>
```
I'm not on Windows and it could help to solve the issue. I would then update the plugin if the solution works

This answer is related to this entry at https://gis.stackexchange.com/a/164119

**Comment by cbredel** [comment]
Thank... It's work ...

**Comment by ThomasG77** [comment]
~~Waiting fix to be published on the official repository :)~~
Published on the official repository
Thanks for your feedback
